version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build debug APK and test APK
          command: |
              ./gradlew :app:assembleDebug
              ./gradlew :app:assembleDebugAndroidTest
      - store_artifacts:
              path: apk/build/outputs/apk/
              destination: /apk/

  test:
      docker:
        - image: circleci/android:api-25-alpha  # gcloud is baked into this image
      steps:
        - run:
            name: Store Google Service Account
            command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
        - run:
            name: Authorize gcloud and set config defaults
            command: |
              sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
              sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
        - run:
            name: Test with Firebase Test Lab
            command: >
              sudo gcloud firebase test android run
                --app app/build/outputs/apk/debug/app-debug.apk
                --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
                --results-bucket cloud-test-${GOOGLE_PROJECT_ID}
        - run:
            name: Install gsutil dependency and copy test results data
            command: |
              sudo pip install -U crcmod
              sudo gsutil -m cp -r -U `sudo gsutil ls gs://score-counter-5541c.appspot.com | tail -1` ${CIRCLE_ARTIFACTS}/ | true
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
